title: Adam Morrissey
logo: "/images/IMG_8047.JPG?raw=true"
description: Data & Analytics Professional specializing in insurance industry intelligence, AI adoption strategy, and value-driven reporting.
linkedin_url: "https://www.linkedin.com/in/adammorrissey/"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
